# Generated by Django 4.1.7 on 2023-03-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
