# Generated by Django 4.1.7 on 2023-03-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='usuario.png', upload_to=''),
        ),
    ]
