# Generated by Django 4.1.7 on 2023-03-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0005_product_post_digital_post_image_post_name_post_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
