# Generated by Django 4.1.7 on 2023-03-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0006_delete_product_rename_content_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
