# Generated by Django 4.1.7 on 2023-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0011_profile_apellidos_profile_direccion_profile_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
