# Generated by Django 4.1.7 on 2023-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0015_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
