# Generated by Django 4.1.7 on 2023-03-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0016_remove_post_post_id_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to='productos'),
        ),
    ]
