# Generated by Django 4.1.7 on 2023-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMC', '0017_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to='usuarios'),
        ),
    ]
